### PR TITLE
add module_config

### PR DESCRIPTION
**Pull request by b4ldr**
a different way to address https://github.com/xaque208/puppet-unbound/pull/174

### CODE REVIEW

**Comment by b4ldr** [comment]
@xaque208 rebased

**Comment by xaque208** [comment]
This looks good, thanks @b4ldr.  What do you think about some tests for the new file contents?

**Comment by b4ldr** [comment]
@xaque208  added tests

**Comment by xaque208** [comment]
Thanks for coming back to this @b4ldr.  You might be able to clear most of those rubocop issues with `bundle exec rubocop -a`.

**Comment by b4ldr** [comment]
omg i  never new you could do that, your my new hero :)

**Comment by xaque208** [comment]
Looks good, thanks for the effort @b4ldr!

**Pull request merged**
