### PR TITLE
Add missing module-config parameter to the template

### PR DESCRIPTION
**Pull request by fklajn-opera**
module-config parameter removed in commit 8ab7ee7cdb7ec940c6f2fabd5c3aadca5a1448e4 is added again

### CODE REVIEW

**Comment by b4ldr** [comment]
@fklajn-opera i wanted to make the module_config option a bit more complete which was why it was removed, however i forgot to actually add it back.  I have now created a new pull request https://github.com/xaque208/puppet-unbound/pull/176 can you take a look at that and comment if it works for your use case

**Comment by b4ldr** [comment]
yes mine is a breaking change, i wonder how many people use this feature,  would be nice to not have to support strings.  will see what @xaque208 says.

out of curiosity how do you use this feature, the current module doesn't allow you to set any parameters for the dns64, cachedb, ipsecmod and python modules unless you use `custom_server_conf`.  are you adding adding config using `custom_server_conf` or are you using this to disable the validator?

**Comment by fklajn-opera** [comment]
In my case this is used only to disable validator, the service resolves internal domains.

**Comment by b4ldr** [comment]
ok thanks

**Comment by xaque208** [comment]
We can take both of these PRs.  @b4ldr If you are good with a merge of this and cutting a point release for it, you can rebase your work  and we'll cut a minor for the breaking change.  Good?

**Comment by b4ldr** [comment]
@xaque208 yes, sounds good to me

**Pull request merged**
