### PR TITLE
add ability for blank pidfile

### PR DESCRIPTION
**Pull request by b4ldr**
allow using a blank pidfile parameter

### CODE REVIEW

**Comment by xaque208** [comment]
This looks reasonable, thanks for the PR  What do you think about a test?

**Comment by b4ldr** [comment]
@xaque208 i refactored the spec file a bit, if you are happy then i will wait for this to get merged and rebase my other PR's and add more tests then

**Comment by xaque208** [comment]
This is good, sorry for the slow response here.

**Comment by xaque208** [comment]
This has been merged.

**Pull request closed without merging**
