### PR TITLE
Add hiera support for define resources

### PR DESCRIPTION
**Pull request by Rocco83**
Hi,
I have added, as it is in apt module, the logic in order to handle definition through hiera.

Regards,
Daniele

### CODE REVIEW

**Comment by xaque208** [comment]
This looks good, thanks for the PR.  How do you feel about a test or three?  This looks like the kind of thing that would be relatively simple to spec test.  The data doesn't need to come from hiera, but could just be passed in at the `unbound` class.

**Comment by Rocco83** [comment]
Hi, i didn't had time yet. I will do it asap.
Cheers

**Comment by Rocco83** [comment]
Hi,
I have created one test for each parameter.
I have choosed this path in order to let the failure happens on one single test.
If you have any suggestion, feel free to do it!

HTH,
Daniele

**Comment by xaque208** [comment]
This is good work, thank you for the efforts.

**Pull request merged**
